### ISSUE TITLE
BigComplexMath.sqrt fails on non-positive real numbers

### ISSUE THREAD

**Issue by noeppi-noeppi** [eobermuhlner/big-math#66]
When `BigComplexMath.sqrt` is invoked with an argument that has a negative or zero real part and a zero imaginary part, it throws an `ArithmeticException`:

```java
BigComplexMath.sqrt(BigComplex.ONE.negate(), MathContext.DECIMAL64)
```

```
Exception in thread "main" java.lang.ArithmeticException: Division undefined
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1831)
	at ch.obermuhlner.math.big.BigComplex.divide(BigComplex.java:287)
	at ch.obermuhlner.math.big.BigComplexMath.sqrt(BigComplexMath.java:289)
```

### Expected behaviour:

`BigComplexMath.sqrt` should not throw an `ArithmeticException` but compute the result (in the above case `0 + 1i`) instead.

**Comment by eobermuhlner** [comment]
The bug is confirmed and I am working on a fix.

Thanks for reporting it.

**Comment by nadment** [comment]
This should also solve a problem with the ACOS function. BigDecimalMath.acosh(BigDecimal.ZERO, MathContext.DECIMAL128);  >>  Illegal sqrt(x) for x < 0: x = -1
